# fly.toml app configuration file generated for indianopenmaps on 2023-08-21T10:33:10+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "indianopenmaps"
primary_region = "bos"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
