events {
    worker_connections 1024;
}

http {
    server {
        listen 8080;
        server_name _;

        location / {
            return 301 https://indianopenmaps.com$request_uri;
        }
    }
}
